// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.client.model.request;

public interface AcceptorRegisterRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.AcceptorRegisterRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string acceptorInstanceId = 1;</code>
   */
  String getAcceptorInstanceId();
  /**
   * <code>string acceptorInstanceId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAcceptorInstanceIdBytes();
}
