// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.client.model.request;

/**
 * Protobuf type {@code com.phantom.protocol.AcceptorRegisterRequest}
 */
public  final class AcceptorRegisterRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.phantom.protocol.AcceptorRegisterRequest)
    AcceptorRegisterRequestOrBuilder {
  // Use AcceptorRegisterRequest.newBuilder() to construct.
  private AcceptorRegisterRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AcceptorRegisterRequest() {
    acceptorInstanceId_ = "";
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private AcceptorRegisterRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            acceptorInstanceId_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Model.internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Model.internal_static_com_phantom_protocol_AcceptorRegisterRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AcceptorRegisterRequest.class, Builder.class);
  }

  public static final int ACCEPTORINSTANCEID_FIELD_NUMBER = 1;
  private volatile Object acceptorInstanceId_;
  /**
   * <code>string acceptorInstanceId = 1;</code>
   */
  public String getAcceptorInstanceId() {
    Object ref = acceptorInstanceId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      acceptorInstanceId_ = s;
      return s;
    }
  }
  /**
   * <code>string acceptorInstanceId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAcceptorInstanceIdBytes() {
    Object ref = acceptorInstanceId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      acceptorInstanceId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAcceptorInstanceIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, acceptorInstanceId_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAcceptorInstanceIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, acceptorInstanceId_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AcceptorRegisterRequest)) {
      return super.equals(obj);
    }
    AcceptorRegisterRequest other = (AcceptorRegisterRequest) obj;

    boolean result = true;
    result = result && getAcceptorInstanceId()
        .equals(other.getAcceptorInstanceId());
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACCEPTORINSTANCEID_FIELD_NUMBER;
    hash = (53 * hash) + getAcceptorInstanceId().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AcceptorRegisterRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AcceptorRegisterRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AcceptorRegisterRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AcceptorRegisterRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AcceptorRegisterRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AcceptorRegisterRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AcceptorRegisterRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AcceptorRegisterRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AcceptorRegisterRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AcceptorRegisterRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AcceptorRegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AcceptorRegisterRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AcceptorRegisterRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.phantom.protocol.AcceptorRegisterRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.phantom.protocol.AcceptorRegisterRequest)
          AcceptorRegisterRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Model.internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Model.internal_static_com_phantom_protocol_AcceptorRegisterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AcceptorRegisterRequest.class, Builder.class);
    }

    // Construct using com.phantom.client.model.request.AcceptorRegisterRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      acceptorInstanceId_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Model.internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor;
    }

    public AcceptorRegisterRequest getDefaultInstanceForType() {
      return AcceptorRegisterRequest.getDefaultInstance();
    }

    public AcceptorRegisterRequest build() {
      AcceptorRegisterRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AcceptorRegisterRequest buildPartial() {
      AcceptorRegisterRequest result = new AcceptorRegisterRequest(this);
      result.acceptorInstanceId_ = acceptorInstanceId_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AcceptorRegisterRequest) {
        return mergeFrom((AcceptorRegisterRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AcceptorRegisterRequest other) {
      if (other == AcceptorRegisterRequest.getDefaultInstance()) return this;
      if (!other.getAcceptorInstanceId().isEmpty()) {
        acceptorInstanceId_ = other.acceptorInstanceId_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AcceptorRegisterRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AcceptorRegisterRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object acceptorInstanceId_ = "";
    /**
     * <code>string acceptorInstanceId = 1;</code>
     */
    public String getAcceptorInstanceId() {
      Object ref = acceptorInstanceId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        acceptorInstanceId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string acceptorInstanceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAcceptorInstanceIdBytes() {
      Object ref = acceptorInstanceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        acceptorInstanceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string acceptorInstanceId = 1;</code>
     */
    public Builder setAcceptorInstanceId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      acceptorInstanceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string acceptorInstanceId = 1;</code>
     */
    public Builder clearAcceptorInstanceId() {
      
      acceptorInstanceId_ = getDefaultInstance().getAcceptorInstanceId();
      onChanged();
      return this;
    }
    /**
     * <code>string acceptorInstanceId = 1;</code>
     */
    public Builder setAcceptorInstanceIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      acceptorInstanceId_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.phantom.protocol.AcceptorRegisterRequest)
  }

  // @@protoc_insertion_point(class_scope:com.phantom.protocol.AcceptorRegisterRequest)
  private static final AcceptorRegisterRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AcceptorRegisterRequest();
  }

  public static AcceptorRegisterRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AcceptorRegisterRequest>
      PARSER = new com.google.protobuf.AbstractParser<AcceptorRegisterRequest>() {
    public AcceptorRegisterRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new AcceptorRegisterRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AcceptorRegisterRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AcceptorRegisterRequest> getParserForType() {
    return PARSER;
  }

  public AcceptorRegisterRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

