// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.client.model.request;

public interface C2CPushMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.C2CPushMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string senderId = 1;</code>
   */
  String getSenderId();
  /**
   * <code>string senderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiverId = 2;</code>
   */
  String getReceiverId();
  /**
   * <code>string receiverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>string content = 4;</code>
   */
  String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();
}
