// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.client.model.request;

public interface InformFetchMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.InformFetchMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
