// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface AuthenticateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.AuthenticateResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string token = 2;</code>
   */
  String getToken();
  /**
   * <code>string token = 2;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 status = 4;</code>
   */
  int getStatus();
}
