// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface C2CMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.C2CMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string senderId = 1;</code>
   */
  String getSenderId();
  /**
   * <code>string senderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiverId = 2;</code>
   */
  String getReceiverId();
  /**
   * <code>string receiverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string crc = 4;</code>
   */
  String getCrc();
  /**
   * <code>string crc = 4;</code>
   */
  com.google.protobuf.ByteString
      getCrcBytes();

  /**
   * <code>int32 platform = 5;</code>
   */
  int getPlatform();
}
