// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface C2CMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.C2CMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string senderId = 1;</code>
   */
  String getSenderId();
  /**
   * <code>string senderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiverId = 2;</code>
   */
  String getReceiverId();
  /**
   * <code>string receiverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 status = 4;</code>
   */
  int getStatus();

  /**
   * <code>string crc = 5;</code>
   */
  String getCrc();
  /**
   * <code>string crc = 5;</code>
   */
  com.google.protobuf.ByteString
      getCrcBytes();

  /**
   * <code>int32 platform = 6;</code>
   */
  int getPlatform();

  /**
   * <code>int64 messageId = 7;</code>
   */
  long getMessageId();
}
