// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface FetchMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.FetchMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool isEmpty = 1;</code>
   */
  boolean getIsEmpty();

  /**
   * <code>repeated .com.phantom.protocol.OfflineMessage messages = 2;</code>
   */
  java.util.List<com.phantom.common.OfflineMessage> 
      getMessagesList();
  /**
   * <code>repeated .com.phantom.protocol.OfflineMessage messages = 2;</code>
   */
  com.phantom.common.OfflineMessage getMessages(int index);
  /**
   * <code>repeated .com.phantom.protocol.OfflineMessage messages = 2;</code>
   */
  int getMessagesCount();
  /**
   * <code>repeated .com.phantom.protocol.OfflineMessage messages = 2;</code>
   */
  java.util.List<? extends com.phantom.common.OfflineMessageOrBuilder> 
      getMessagesOrBuilderList();
  /**
   * <code>repeated .com.phantom.protocol.OfflineMessage messages = 2;</code>
   */
  com.phantom.common.OfflineMessageOrBuilder getMessagesOrBuilder(
          int index);

  /**
   * <code>string uid = 3;</code>
   */
  String getUid();
  /**
   * <code>string uid = 3;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
