// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface FetchMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.FetchMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1;</code>
   */
  String getUid();
  /**
   * <code>string uid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 platform = 4;</code>
   */
  int getPlatform();
}
