// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public final class Model {
  private Model() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_AuthenticateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_AuthenticateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_AuthenticateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_AuthenticateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_AcceptorRegisterRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_C2CMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_C2CMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_C2CMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_C2CMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_C2CPushMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_C2CPushMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_InformFetchMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_InformFetchMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_FetchMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_FetchMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_FetchMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_FetchMessageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_OfflineMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_OfflineMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_C2GMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_C2GMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_phantom_protocol_C2GMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_phantom_protocol_C2GMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013model.proto\022\024com.phantom.protocol\"1\n\023A" +
      "uthenticateRequest\022\013\n\003uid\030\001 \001(\t\022\r\n\005token" +
      "\030\002 \001(\t\"U\n\024AuthenticateResponse\022\013\n\003uid\030\001 " +
      "\001(\t\022\r\n\005token\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\022\016\n" +
      "\006status\030\004 \001(\005\"5\n\027AcceptorRegisterRequest" +
      "\022\032\n\022acceptorInstanceId\030\001 \001(\t\"\\\n\021C2CMessa" +
      "geRequest\022\020\n\010senderId\030\001 \001(\t\022\022\n\nreceiverI" +
      "d\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\020\n\010sequence\030\004 \001" +
      "(\003\"]\n\022C2CMessageResponse\022\020\n\010senderId\030\001 \001" +
      "(\t\022\022\n\nreceiverId\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(",
      "\003\022\016\n\006status\030\004 \001(\005\"a\n\025C2CPushMessageReque" +
      "st\022\020\n\010senderId\030\001 \001(\t\022\022\n\nreceiverId\030\002 \001(\t" +
      "\022\021\n\ttimestamp\030\003 \001(\003\022\017\n\007content\030\004 \001(\t\")\n\032" +
      "InformFetchMessageResponse\022\013\n\003uid\030\001 \001(\t\"" +
      "U\n\023FetchMessageRequest\022\013\n\003uid\030\001 \001(\t\022\014\n\004s" +
      "ize\030\002 \001(\005\022\021\n\ttimestamp\030\003 \001(\003\022\020\n\010platform" +
      "\030\004 \001(\005\"l\n\024FetchMessageResponse\022\017\n\007isEmpt" +
      "y\030\001 \001(\010\0226\n\010messages\030\002 \003(\0132$.com.phantom." +
      "protocol.OfflineMessage\022\013\n\003uid\030\003 \001(\t\"\220\001\n" +
      "\016OfflineMessage\022\020\n\010senderId\030\001 \001(\t\022\022\n\nrec",
      "eiverId\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\021\n\ttimest" +
      "amp\030\004 \001(\003\022\021\n\tmessageId\030\005 \001(\003\022\017\n\007groupId\030" +
      "\006 \001(\t\022\020\n\010sequence\030\007 \001(\003\"Z\n\021C2GMessageReq" +
      "uest\022\020\n\010senderId\030\001 \001(\t\022\017\n\007groupId\030\002 \001(\t\022" +
      "\021\n\ttimestamp\030\003 \001(\003\022\017\n\007content\030\004 \001(\t\"Z\n\022C" +
      "2GMessageResponse\022\020\n\010senderId\030\001 \001(\t\022\017\n\007g" +
      "roupId\030\002 \001(\t\022\021\n\ttimestamp\030\003 \001(\003\022\016\n\006statu" +
      "s\030\004 \001(\005B\026\n\022com.phantom.commonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_phantom_protocol_AuthenticateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_phantom_protocol_AuthenticateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_AuthenticateRequest_descriptor,
        new String[] { "Uid", "Token", });
    internal_static_com_phantom_protocol_AuthenticateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_phantom_protocol_AuthenticateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_AuthenticateResponse_descriptor,
        new String[] { "Uid", "Token", "Timestamp", "Status", });
    internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_phantom_protocol_AcceptorRegisterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_AcceptorRegisterRequest_descriptor,
        new String[] { "AcceptorInstanceId", });
    internal_static_com_phantom_protocol_C2CMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_phantom_protocol_C2CMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_C2CMessageRequest_descriptor,
        new String[] { "SenderId", "ReceiverId", "Content", "Sequence", });
    internal_static_com_phantom_protocol_C2CMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_phantom_protocol_C2CMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_C2CMessageResponse_descriptor,
        new String[] { "SenderId", "ReceiverId", "Timestamp", "Status", });
    internal_static_com_phantom_protocol_C2CPushMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_phantom_protocol_C2CPushMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_C2CPushMessageRequest_descriptor,
        new String[] { "SenderId", "ReceiverId", "Timestamp", "Content", });
    internal_static_com_phantom_protocol_InformFetchMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_phantom_protocol_InformFetchMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_InformFetchMessageResponse_descriptor,
        new String[] { "Uid", });
    internal_static_com_phantom_protocol_FetchMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_phantom_protocol_FetchMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_FetchMessageRequest_descriptor,
        new String[] { "Uid", "Size", "Timestamp", "Platform", });
    internal_static_com_phantom_protocol_FetchMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_phantom_protocol_FetchMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_FetchMessageResponse_descriptor,
        new String[] { "IsEmpty", "Messages", "Uid", });
    internal_static_com_phantom_protocol_OfflineMessage_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_phantom_protocol_OfflineMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_OfflineMessage_descriptor,
        new String[] { "SenderId", "ReceiverId", "Content", "Timestamp", "MessageId", "GroupId", "Sequence", });
    internal_static_com_phantom_protocol_C2GMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_phantom_protocol_C2GMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_C2GMessageRequest_descriptor,
        new String[] { "SenderId", "GroupId", "Timestamp", "Content", });
    internal_static_com_phantom_protocol_C2GMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_phantom_protocol_C2GMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_phantom_protocol_C2GMessageResponse_descriptor,
        new String[] { "SenderId", "GroupId", "Timestamp", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
