// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package com.phantom.common;

public interface OfflineMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.phantom.protocol.OfflineMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string senderId = 1;</code>
   */
  String getSenderId();
  /**
   * <code>string senderId = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderIdBytes();

  /**
   * <code>string receiverId = 2;</code>
   */
  String getReceiverId();
  /**
   * <code>string receiverId = 2;</code>
   */
  com.google.protobuf.ByteString
      getReceiverIdBytes();

  /**
   * <code>string content = 3;</code>
   */
  String getContent();
  /**
   * <code>string content = 3;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>int64 timestamp = 4;</code>
   */
  long getTimestamp();

  /**
   * <code>int64 messageId = 5;</code>
   */
  long getMessageId();

  /**
   * <code>string groupId = 6;</code>
   */
  String getGroupId();
  /**
   * <code>string groupId = 6;</code>
   */
  com.google.protobuf.ByteString
      getGroupIdBytes();

  /**
   * <code>int64 sequence = 7;</code>
   */
  long getSequence();
}
